import { useMemo, useEffect } from 'react';
import { useWallet } from '@provablehq/aleo-wallet-adaptor-react';
import { prepareApproveOp, submitApproveOp } from '@fairdrop/sdk/multisig';
import { type TxSpec }                       from '@fairdrop/sdk/transactions';
import {
  useConfirmedSequentialTx,
  type SequentialStep,
} from '@/shared/hooks/useConfirmedSequentialTx';
import type { ThreeSigs } from '../../types';

interface TwoPhaseOpOptions {
  /** BHP256(OpStruct) — computed by the caller using the relevant computeXxxOpHash. */
  opHash:      string;
  /** Unique u64 — generated by generateNonce(), must match the one signed by admins. */
  requestId:   bigint;
  /** 3 sig + admin pairs collected from SignaturePanel. */
  sigs:        ThreeSigs;
  /** Human-readable label for the second (execution) step. */
  phase2Label: string;
  /** Builds the target setter TxSpec (same opNonce used when computing opHash). */
  buildPhase2: () => TxSpec;
}

/**
 * Two-phase governance operation hook.
 *
 * Phase 1 — approve_op: writes approved_ops[opHash] = true in fairdrop_multisig.
 * Phase 2 — execute: calls the target setter (config, set_allowed_caller, etc.).
 *
 * Returns msgHash for display in MsgHashPanel plus the full useConfirmedSequentialTx state.
 */
export function useTwoPhaseOp({
  opHash,
  requestId,
  sigs,
  phase2Label,
  buildPhase2,
}: TwoPhaseOpOptions) {
  const { executeTransaction } = useWallet();
  const msgHash = opHash ? prepareApproveOp(opHash, requestId).msgHash : '';

  const steps = useMemo<SequentialStep[]>(() => [
    {
      label: 'Submit approval',
      execute: async () => {
        const spec = submitApproveOp(
          opHash,
          sigs[0].sig,   sigs[0].admin,
          sigs[1].sig,   sigs[1].admin,
          sigs[2].sig,   sigs[2].admin,
          requestId,
        );
        const result = await executeTransaction({ ...spec, inputs: spec.inputs as string[] });
        return result?.transactionId;
      },
    },
    {
      label: phase2Label,
      execute: async () => {
        const spec = buildPhase2();
        const result = await executeTransaction({ ...spec, inputs: spec.inputs as string[] });
        return result?.transactionId;
      },
    },
  // eslint-disable-next-line react-hooks/exhaustive-deps
  ], [opHash, requestId, sigs, phase2Label, buildPhase2]);

  const seqTx = useConfirmedSequentialTx(steps);

  // Auto-fire phase 2 after phase 1 (approve_op) confirms on-chain.
  useEffect(() => {
    if (seqTx.currentStep === 1 && !seqTx.busy && !seqTx.isWaiting && !seqTx.done && !seqTx.error) {
      void seqTx.advance();
    }
  }, [seqTx.currentStep, seqTx.busy, seqTx.isWaiting, seqTx.done, seqTx.error, seqTx.advance]);

  return { msgHash, ...seqTx };
}
