#!/usr/bin/env node
import { fileURLToPath } from 'node:url';
import type { Abi } from '../runtime/abi';
import { emitStructs }          from './structs';
import { emitRecords }          from './records';
import { emitTransitions }      from './transitions';
import { emitClientInterface }  from './client';
import { collectPrimitiveImports, plaintextToTsType, inputToTsType } from './utils';

// ── Code generation ───────────────────────────────────────────────────────────

export function generateTypes(abi: Abi): string {
  // Collect which branded primitive types are actually used
  const usedTypes: string[] = [];
  for (const s of abi.structs) {
    for (const f of s.fields) usedTypes.push(plaintextToTsType(f.ty));
  }
  for (const r of abi.records) {
    for (const f of r.fields) usedTypes.push(plaintextToTsType(f.ty));
  }
  for (const fn of abi.functions) {
    for (const inp of fn.inputs) {
      if (inp.ty !== 'Final' && !('Record' in inp.ty)) {
        try { usedTypes.push(inputToTsType(inp.ty)); } catch { /* skip */ }
      }
    }
  }
  const brandedImports = collectPrimitiveImports(usedTypes);
  const needsWalletRecord = abi.records.length > 0;

  const sections: string[] = [];

  // Header
  sections.push('// auto-generated by leo-abigen — do not edit');
  sections.push(`// source: ${abi.program}`);
  sections.push('');

  // Imports
  if (abi.records.length > 0) {
    sections.push('import { createRecordScanner }                         from "@fairdrop/leo-abigen";');
    sections.push('import type { TransitionHandle, TxOptions, AbiRecord, AbiStruct } from "@fairdrop/leo-abigen";');
  } else {
    sections.push('import type { TransitionHandle, TxOptions }            from "@fairdrop/leo-abigen";');
  }

  const primitiveImports: string[] = [...brandedImports];
  if (needsWalletRecord) primitiveImports.push('WalletRecord');
  if (primitiveImports.length > 0) {
    const typeImports = brandedImports.join(', ');
    if (needsWalletRecord) {
      sections.push(`import type { ${typeImports ? typeImports + ', ' : ''}WalletRecord } from "@fairdrop/types/primitives";`);
    } else if (typeImports) {
      sections.push(`import type { ${typeImports} }                       from "@fairdrop/types/primitives";`);
    }
  }
  sections.push('');

  // Body
  const structs = emitStructs(abi.structs);
  if (structs) sections.push(structs);

  const records = emitRecords(abi.records, abi.structs);
  if (records) sections.push(records);

  const transitions = emitTransitions(abi.functions);
  if (transitions) sections.push(transitions);

  const client = emitClientInterface(abi);
  if (client) sections.push(client);

  return sections.join('\n');
}

// ── CLI ───────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const args = process.argv.slice(2);

  const abiFlag = args.indexOf('--abi');
  const outFlag = args.indexOf('--out');

  if (abiFlag === -1 || !args[abiFlag + 1]) {
    console.error('Usage: leo-abigen --abi <path/to/abi.json> --out <path/to/output.ts>');
    process.exit(1);
  }

  const abiPath = args[abiFlag + 1]!;
  const outPath = outFlag !== -1 && args[outFlag + 1] ? args[outFlag + 1]! : null;

  const { readFile, writeFile } = await import('node:fs/promises');
  const { resolve, dirname }    = await import('node:path');
  const { mkdirSync }           = await import('node:fs');

  const raw = await readFile(abiPath, 'utf-8');
  const abi = JSON.parse(raw) as Abi;
  const output = generateTypes(abi);

  if (outPath) {
    const resolved = resolve(outPath);
    mkdirSync(dirname(resolved), { recursive: true });
    await writeFile(resolved, output, 'utf-8');
    console.log(`[leo-abigen] generated ${resolved}`);
  } else {
    process.stdout.write(output);
  }
}

// Only execute as CLI when invoked directly — not when imported as a module.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch(err => {
    console.error('[leo-abigen]', err);
    process.exit(1);
  });
}
